// Multilingual helpers. INS labels are French only, but users (and models)
// ask in English or Arabic. These tables bridge the gap without any
// translation service.

/**
 * English search terms -> French word prefixes used in INS indicator names.
 * Matching works on normalized word prefixes, so "chom" covers chômage and
 * chômeurs. Each English word may map to several alternatives (OR).
 * Multi-word English phrases are listed first and replaced before splitting.
 */
export const EN_PHRASES: [string, string][] = [
	["labor force", "active"],
	["labour force", "active"],
	["exchange rate", "change"],
	["interest rate", "interet"],
	["money supply", "monnaie"],
	["gross domestic product", "pib"],
	["consumer price", "prix consommation"],
	["consumer prices", "prix consommation"],
	["olive oil", "huile olive"],
	["trade balance", "balance commerciale"],
	["birth rate", "natalite"],
	["death rate", "mortalite"],
	["life expectancy", "esperance vie"],
	["value added", "valeur ajoutee"],
	["foreign trade", "echanges exterieurs"],
	["current account", "courante"],
];

export const EN_WORDS: Record<string, string[]> = {
	unemployment: ["chom"],
	unemployed: ["chom"],
	jobless: ["chom"],
	employment: ["emploi", "occup"],
	employed: ["occup"],
	jobs: ["emploi"],
	workforce: ["active"],
	population: ["population"],
	inhabitants: ["habitant", "population"],
	people: ["population"],
	inflation: ["prix", "glissement"],
	cpi: ["ipc", "prix"],
	prices: ["prix"],
	price: ["prix"],
	gdp: ["pib", "produit interieur"],
	growth: ["croissance", "evolution"],
	exports: ["export"],
	export: ["export"],
	imports: ["import"],
	import: ["import"],
	trade: ["echange", "commerc"],
	births: ["naissance", "natalite"],
	birth: ["naissance", "natalite"],
	deaths: ["deces", "mortalite"],
	death: ["deces", "mortalite"],
	marriages: ["mariage"],
	marriage: ["mariage"],
	divorces: ["divorce"],
	tourism: ["touris"],
	tourists: ["touris"],
	tourist: ["touris"],
	overnight: ["nuitee"],
	nights: ["nuitee"],
	hotels: ["hotel", "hotel"],
	agriculture: ["agric"],
	agricultural: ["agric"],
	farm: ["agric"],
	production: ["production"],
	olive: ["olive"],
	oil: ["huile", "petrol"],
	wheat: ["ble"],
	cereals: ["cereal"],
	dates: ["datte"],
	citrus: ["agrume"],
	fishing: ["peche"],
	fish: ["poisson", "peche"],
	livestock: ["elevage", "cheptel"],
	energy: ["energ"],
	electricity: ["electric"],
	gas: ["gaz"],
	water: ["eau"],
	school: ["ecole", "scolar"],
	schools: ["ecole", "scolar"],
	pupils: ["eleve"],
	students: ["etudiant", "eleve"],
	university: ["universit", "superieur"],
	teachers: ["enseignant"],
	education: ["enseignement", "education", "scolar"],
	literacy: ["alphabet"],
	illiteracy: ["analphabet"],
	health: ["sante"],
	doctors: ["medecin"],
	hospitals: ["hopita"],
	beds: ["lit"],
	wages: ["salaire"],
	wage: ["salaire"],
	salary: ["salaire"],
	income: ["revenu"],
	households: ["menage"],
	household: ["menage"],
	housing: ["logement"],
	dwellings: ["logement"],
	vehicles: ["vehicule"],
	cars: ["voiture", "vehicule"],
	accidents: ["accident"],
	companies: ["entreprise", "societe"],
	enterprises: ["entreprise"],
	firms: ["entreprise"],
	investment: ["investissement"],
	investments: ["investissement"],
	debt: ["dette", "endettement"],
	budget: ["budget"],
	revenue: ["recette"],
	expenditure: ["depense"],
	spending: ["depense"],
	consumption: ["consommation"],
	bank: ["banque", "bancaire"],
	banks: ["banque", "bancaire"],
	credit: ["credit"],
	loans: ["credit", "pret"],
	deposits: ["depot"],
	money: ["monnaie", "monetaire"],
	reserves: ["reserve"],
	industry: ["industri"],
	industrial: ["industri"],
	manufacturing: ["manufactur", "industri"],
	mining: ["mine", "extracti"],
	phosphate: ["phosphate"],
	construction: ["construction", "batiment"],
	cement: ["ciment"],
	rainfall: ["pluvio", "pluie"],
	poverty: ["pauvrete"],
	women: ["femin", "femme"],
	female: ["femin"],
	men: ["masculin", "homme"],
	male: ["masculin"],
	youth: ["jeune"],
	rural: ["rural"],
	urban: ["urbain", "communal"],
	migration: ["migra"],
	migrants: ["migra"],
	internet: ["internet"],
	mobile: ["mobile"],
	telephone: ["telephon"],
	transport: ["transport"],
	airport: ["aero"],
	passengers: ["passager", "voyageur"],
	ports: ["port"],
	rate: ["taux"],
	index: ["indice"],
	average: ["moyen"],
	total: ["total", "ensemble"],
	annual: ["annuel"],
	monthly: ["mensuel"],
	age: ["age"],
	sex: ["sexe"],
	gender: ["sexe", "genre"],
	density: ["densite"],
	area: ["superficie"],
	projection: ["projection"],
	projections: ["projection"],
	census: ["recensement"],
};

/** Governorates by ISO code: Arabic name and common English/alternative spellings. */
export const GOVERNORATE_NAMES: Record<string, { ar: string; alt: string[] }> = {
	"TN-11": { ar: "تونس", alt: [] },
	"TN-12": { ar: "أريانة", alt: ["ariana", "ariane"] },
	"TN-13": { ar: "بن عروس", alt: ["ben arous"] },
	"TN-14": { ar: "منوبة", alt: ["manouba", "mannouba"] },
	"TN-21": { ar: "نابل", alt: ["nabeul"] },
	"TN-22": { ar: "زغوان", alt: ["zaghouan"] },
	"TN-23": { ar: "بنزرت", alt: ["bizerte", "bizerta", "benzart"] },
	"TN-31": { ar: "باجة", alt: ["beja", "bajah"] },
	"TN-32": { ar: "جندوبة", alt: ["jendouba", "jandouba"] },
	"TN-33": { ar: "الكاف", alt: ["kef", "el kef", "le kef"] },
	"TN-34": { ar: "سليانة", alt: ["siliana"] },
	"TN-41": { ar: "القيروان", alt: ["kairouan", "kairuan", "qairawan"] },
	"TN-42": { ar: "القصرين", alt: ["kasserine", "kasrine"] },
	"TN-43": { ar: "سيدي بوزيد", alt: ["sidi bouzid", "sidi bou zid"] },
	"TN-51": { ar: "سوسة", alt: ["sousse", "susa"] },
	"TN-52": { ar: "المنستير", alt: ["monastir"] },
	"TN-53": { ar: "المهدية", alt: ["mahdia"] },
	"TN-61": { ar: "صفاقس", alt: ["sfax", "safaqis"] },
	"TN-71": { ar: "قفصة", alt: ["gafsa"] },
	"TN-72": { ar: "توزر", alt: ["tozeur"] },
	"TN-73": { ar: "قبلي", alt: ["kebili", "kibili", "qibili"] },
	"TN-81": { ar: "قابس", alt: ["gabes", "qabis"] },
	"TN-82": { ar: "مدنين", alt: ["medenine", "madanin"] },
	"TN-83": { ar: "تطاوين", alt: ["tataouine", "tatawin"] },
};

/** Normalize Arabic for matching: drop diacritics/tatweel, unify alef/ta-marbuta/ya forms. */
export function normalizeArabic(s: string): string {
	return s
		.trim()
		.replace(/^ولاية\s+/, "") // "wilaya of", must go before the ta-marbuta rewrite
		.replace(/[ً-ْـ]/g, "")
		.replace(/[أإآ]/g, "ا")
		.replace(/ة/g, "ه")
		.replace(/ى/g, "ي")
		.replace(/\s+/g, " ")
		.trim();
}

export const hasArabic = (s: string) => /[؀-ۿ]/.test(s);
